#!/usr/bin/env bash
# installs and configures nginx web server

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.nginx-debian.html
new_confi=\
"server {
        listen 80;
        listen [::]:80;

        server_name example.com;

        root /var/www/example.com;
        index index.html;

        location / {
                 try_files $uri $uri/ =404;
        }
        if (\$request_filename ~ redirect_me){
                rewrite ^ https://sketchfab.com/bluepeno/models permanent;
        }
}"

sudo echo -e $new_config > /etc/nginx/sites-enabled/default
sudo service nginx start
