#!/usr/bin/env bash
# sets a custom 404 page

# install nginx if it doesn't exist
sudo apt-get -y update
sudo apt-get -y install nginx

# listen to http requests and change the default html to serve hello world
sudo ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.nginx-debian.html

# Creating variable of lines to add to config file that redirect to other url
line1="\n\t}\n\tif (\$uri ~* \"redirect_me\") {"
line2="\t\trewrite ^ https://www.youtube.com/watch?v=xvFZjo5PgG0&pp=ygUJcmljayByb2xs permanent;"

temp=$(mktemp)
echo -e "$line1" >> "$temp"
echo -e "$line2" >> "$temp"

# add the lines to the file right below the location / block
sudo sed -i "\/^\\t\\ttry_files \$uri \$uri\/ \=404\;/r $temp" /etc/nginx/sites-available/default

# Create an error file that contains custom error message
echo "Ceci n'est pas une page" > error.html

# move the file to default web location
sudo mv error.html /var/www/html

# create lines that will be added to the config file the create our custom error message
err_line1="\n\t}\n\terror_page 404 /error.html;"
err_line2="\tlocation = /error.html {"
err_line3="\t\tinternal;\n\t"

errtemp=$(mktemp)
{
        echo -e "$err_line1"
        echo -e "$err_line2"
        echo -e "$err_line3"
} >> "$errtemp"

#adding them right below the location / block in the config file
sudo sed -i "\/^\\t\\ttry_files \$uri \$uri\/ \=404\;/r $errtemp" /etc/nginx/sites-available/default

sudo service nginx restart
