#!/usr/bin/env bash
# configures a custom respones header

hname=$(hostname)
config="\t\tadd_header X-Server-By ${hname};"

sudo sed -i "\/^\\t\\ttry_files \$uri \$uri\/ \=404\;/a \\$config" /etc/nginx/sites-enabled/default
sudo service nginx start
