#!/usr/bin/env bash
# configures a custom respones header
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.nginx-debian.html

line1="\n\t}\n\tif (\$uri ~* \"redirect_me\") {"
line2="\t\trewrite ^ https://www.youtube.com/watch?v=xvFZjo5PgG0&pp=ygUJcmljayByb2xs permanent;"

temp=$(mktemp)
echo -e "$line1" >> "$temp"
echo -e "$line2" >> "$temp"

sudo sed -i "\/^\\t\\ttry_files \$uri \$uri\/ \=404\;/r $temp" /etc/nginx/sites-enabled/default

echo "Ceci n'est pas une page" > error.html
sudo mv error.html /var/www/html

err_line1="\n\t}\n\terror_page 404 /error.html;"
err_line2="\tlocation = /error.html {"
err_line3="\t\tinternal;\n\t}"

errtemp=$(mktemp)
{
        echo -e "$err_line1"
        echo -e "$err_line2"
        echo -e "$err_line3"
} >> "$errtemp"

sudo sed -i "\/^\\t\\ttry_files \$uri \$uri\/ \=404\;/r $errtemp" /etc/nginx/sites-enabled/default

hname=$(hostname)
config="\t\tadd_header X-Server-By \"${hname}\";"

sudo sed -i "\/^\\t\\ttry_files \$uri \$uri\/ \=404\;/a \\$config" /etc/nginx/sites-enabled/default
sudo service nginx start
