#!/usr/bin/env bash
# installs and configures HAProxy load balancer

sudo apt-get -y install --no-install-recommends software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.8
sudo apt-get -y install haproxy=2.8.\*

sudo sed -i 's/ENABLED=0/ENABLED=1/g' /etc/default/haproxy
sudo grep -qxF 'ENABLED=1' /etc/default/haproxy || echo 'ENABLED=1' | sudo tee -a /etc/default/haproxy

config="listen load_balancer\n\tbind *:80\n\tmode http\n\tbalance roundrobin\n\toption httpclose\n\toption forwardfor\n\tserver 208163-web-01 100.25.2.66:80 check\n\tserver 208163-web-02 54.159.26.115:80 check"

echo -e ${config} >> /etc/haproxy/haproxy.cfg
sudo service haproxy start
