#!/usr/bin/env bash
# installs and configures HAProxy load balancer

sudo apt-get -y install --no-install-recommends software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.0
sudo apt-get -y update
sudo apt-get -y install haproxy=2.0.\*

echo 'ENABLED=1' >> /etc/default/haproxy

frontend="frontend http\n\tbind *:80\n\tmode http\n\tdefault_backend allservers\n\n"
backend="backend allservers\n\tmode http\n\tserver 208163-web-01 100.25.2.66:80 check\n\tserver 208163-web-02 54.159.26.115:80 check\n"

echo -e ${frontend} >> /etc/haproxy/haproxy.cfg
echo -e ${backend} >> /etc/haproxy/haproxy.cfg

sudo service haproxy restart
