#!/usr/bin/env bash
# creates a backup of all the databases
mysqldump -u root -p $1 --all-databases > backup.sql
day=$(date +%d)
month=$(date +%m)
year=$(date +%Y)
file="${day}-${month}-${year}"
tar -czvf "${filename}.tar.gz" $filename
