#!/usr/bin/env bash
#prints in loop "bad luck" for 4th iteration, "good luck" for 8th, "Best School" for the rest
i=0
while (("$i" < 10))
do
if (("$i" == 3))
then
    echo "bad luck"
elif (("$i" == 7))
then
    echo "good luck"
else
    echo "Best School"
fi
i=("$i"+1)
done
