#!/usr/bin/env bash
# prints 59 min for each hour for 12 hours
hour=0
while (("$hour" < 13))
do
	minute=1
	echo "Hour: " $hour
	while (("$minute" < 60))
    	do
    		echo $((minute%60))
    		minute=$((minute+1))
    	done
	hour=$((hour+1))
done    
