#!/usr/bin/env bash
# runs nginx on the user nginx not as root
echo "user nginx;" >> /etc/nginx/nginx.conf
pkill apache2
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
sudo -u nginx service nginx start
